Update patch set 1
Patch Set 1:

Are we missing an openmp patch:


FAILED: /buildbot/src/android/master-plus-llvm/out/stage2-install/bin/clang++  --sysroot=/buildbot/src/android/master-plus-llvm/out/sysroots/ndk/arm   -Iruntime/src -I/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src -I/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/i18n -I/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/include -I/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/thirdparty/ittnotify -fdebug-prefix-map=/buildbot/src/android/master-plus-llvm= --target=arm-linux-android -B/buildbot/src/android/master-plus-llvm/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -D__ANDROID_API__=16 -ffunction-sections -fdata-sections -march=armv7-a -nostdinc++ -isystem /buildbot/src/android/master-plus-llvm/toolchain/prebuilts/ndk/r20/sources/cxx-stl/llvm-libc++/include -isystem /buildbot/src/android/master-plus-llvm/toolchain/prebuilts/ndk/r20/sources/cxx-stl/llvm-libc++abi/include -isystem /buildbot/src/android/master-plus-llvm/toolchain/prebuilts/ndk/r20/sources/android/support/include -fPIC -Wall -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-extra -Wno-pedantic -std=gnu++11 -O3 -DNDEBUG   -D _GNU_SOURCE -D _REENTRANT -fno-exceptions -fno-rtti -Wno-covered-switch-default -Wno-missing-braces -Wno-strict-aliasing -Wno-switch -Wno-uninitialized -MD -MT runtime/src/CMakeFiles/omp.dir/kmp_i18n.cpp.o -MF runtime/src/CMakeFiles/omp.dir/kmp_i18n.cpp.o.d -o runtime/src/CMakeFiles/omp.dir/kmp_i18n.cpp.o -c /buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/kmp_i18n.cpp
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/kmp_i18n.cpp:123:9: error: use of undeclared identifier 'catopen'
  cat = catopen(name, 0);
        ^
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/kmp_i18n.cpp:156:41: error: use of undeclared identifier 'catgets'
    __kmp_str_buf_print(&version, "%s", catgets(cat, section, number, NULL));
                                        ^
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/kmp_i18n.cpp:181:5: error: use of undeclared identifier 'catclose'
    catclose(cat);
    ^
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/kmp_i18n.cpp:199:19: error: use of undeclared identifier 'catgets'
        message = catgets(cat, section, number,
                  ^
4 errors generated.
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/kmp_str.cpp:694:12: warning: implicit conversion from 'unsigned long long' to 'size_t' (aka 'unsigned int') changes value from 18446744073709551615 to 4294967295 [-Wconstant-conversion]
    *out = KMP_SIZE_T_MAX;
         ~ ^~~~~~~~~~~~~~
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/kmp_os.h:178:25: note: expanded from macro 'KMP_SIZE_T_MAX'
#define KMP_SIZE_T_MAX (0xFFFFFFFFFFFFFFFF)
                        ^~~~~~~~~~~~~~~~~~
1 warning generated.
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/z_Linux_util.cpp:426:7: warning: unused variable 'status' [-Wunused-variable]
  int status;
      ^
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/z_Linux_util.cpp:498:7: warning: unused variable 'status' [-Wunused-variable]
  int status, old_type, old_state;
      ^
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/z_Linux_util.cpp:498:15: warning: unused variable 'old_type' [-Wunused-variable]
  int status, old_type, old_state;
              ^
/buildbot/src/android/master-plus-llvm/toolchain/llvm-project/openmp/runtime/src/z_Linux_util.cpp:498:25: warning: unused variable 'old_state' [-Wunused-variable]
  int status, old_type, old_state;
                        ^
4 warnings generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "toolchain/llvm_android/build.py", line 1923, in <module>
    main()
  File "toolchain/llvm_android/build.py", line 1887, in main
    build_runtimes(stage2_install)
  File "toolchain/llvm_android/build.py", line 1419, in build_runtimes
    build_libomp(stage2_install, version, ndk_cxx=True)
  File "toolchain/llvm_android/build.py", line 740, in build_libomp
    install=False)
  File "toolchain/llvm_android/build.py", line 366, in invoke_cmake
    check_call([ninja_bin_path()] + ninja_target, cwd=out_path, env=env)
  File "toolchain/llvm_android/build.py", line 60, in check_call
    subprocess.check_call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/buildbot/src/android/master-plus-llvm/prebuilts/cmake/linux-x86/bin/ninja']' returned non-zero exit status 1

Patch-set: 1